# NumPy Basics

NumPy is a numerical Python, and it has a lot of capabilities to working with data in similar way as Pandas.

In [2]:
import numpy as np

## Introduction to NumPy Arrays

NumPy (Numerical Python) is an essential library for working with dimensional arrays (matrices and vectors). Because NumPy has optimizations it is usually much faster than working with Python when processing data.

It's the library that actually Pandas uses to do all of those operations.

Arrays are homogenous, that is, it's items must be of the same type (unlike a Python list).

### Create arrays with lists

In [3]:
# Single dimension arrays
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [5]:
# two dimensions 
array = np.array([[1, 2], [2, 2]])
print(array.shape)
array

(2, 2)


array([[1, 2],
       [2, 2]])

### Create arrays with built-in functions

In [6]:
# 2 x 2 array with random floats of 0 to 1
np.random.rand(2, 2) 

array([[0.78773049, 0.83156255],
       [0.83359164, 0.65298833]])

In [7]:
# fill out the 3 x 4 array with the number 8
np.full((3, 4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [8]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# a simple sequence from 0 to 4
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [11]:
# a sequence with 3 steps from 0 to 27
np.arange(0, 27, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

## Common NumPy Array Operations

In [12]:
# An array with weight in pounds
array = np.array([140, 174, 166, 192])
array

array([140, 174, 166, 192])

In [14]:
# Divide by 2.2 to get values in kilos
array/2.2

array([63.63636364, 79.09090909, 75.45454545, 87.27272727])

### Reshaping arrays

Reshaping has to keep the same number of items.

In [15]:
array = np.ones((3, 4))
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
print(array.reshape(4, 3))
print()
print(array.reshape(2, 6))
print()
print(array.reshape(1, 12))
print()
print(array.reshape(12, 1))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [21]:
# Flatten arrays
print(array)
print()
print(array.flatten())

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## More NumPy Array Operations

### Expanding arrays

In [24]:
array = np.ones((4,))
print(array)
print(array.shape)

expanded = array[np.newaxis, :]
print(expanded)
print(expanded.shape)

[1. 1. 1. 1.]
(4,)
[[1. 1. 1. 1.]]
(1, 4)


### Condition new arrays

In [25]:
array = np.array([[3, 12, 11], [45, 22, 11], [56, 15, 22]])
print(array < 20)

[[ True  True  True]
 [False False  True]
 [False  True False]]


In [26]:
print(array[array < 20])

[ 3 12 11 11 15]


### Slicing

In [28]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [29]:
a[1:4]

array([1, 2, 3])

### Stacking

In [34]:
# Horizontal
first = np.full((2, 12), 2)
print(first)
print()
second = np.full((2, 7), 2)
print(second)
print()
print(np.hstack((first, second)))

[[2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2]]

[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]

[[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]]


In [35]:
# Vertically
first = np.full((3, 3), 1)
print(first)
print()
second = np.full((3, 3), 5)
print(second)
print()
print(np.vstack((first, second)))

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[5 5 5]
 [5 5 5]
 [5 5 5]]

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


### Split arrays

In [36]:
array = np.arange(1, 11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [40]:
# Split into 2 equals parts. It needs to allow for an equal division

print(np.hsplit(array, 2))
print(np.hsplit(array, 5))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


In [42]:
# Unpacking
first, second = np.hsplit(array, 2)
print(first)
print()
print(second)

[1 2 3 4 5]

[ 6  7  8  9 10]
